name: DEI Applicant form for In-Person Event
description: Fill the application form
title: "[Application]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the DEI badging application.
  - type: input
    id: Eventname
    attributes:
      label: Event Name
      description: What's the event name
      placeholder: ex. Chaoss conferrence
    validations:
      required: false
  - type: input
    id: WebsiteLink
    attributes:
      label: Link to the website
      description: Enter the link of the event website
    validations:
      required: true
  - type: dropdown
    id: isEventOrganiser
    attributes:
      label: Are you an event organizer?
      description: Select Yes/No
      options:
        - Yes
        - No
    validations:
      required: true